### ISSUE TITLE
Ajouter Saint Martin

### ISSUE THREAD

**Issue by guillett** [etalab/decoupage-administratif#1]
Salut, ce que vous faites c'est top !

L'API Géo connaît bien Saint Martin `https://geo.api.gouv.fr/communes?codePostal=97150`
```json
[{"nom":"Saint-Martin","code":"97801","codesPostaux":["97150"],"population":35594}]
```

Je n'arrive pas à trouver Saint Martin dans ce paquet. La commande suivante renvoie rien.
```
var communes = require('@etalab/decoupage-administratif/data/communes.json');
communes.filter(function(c) { return c.code == '97801'; })
```

J'ai regardé dans [`codes-postaux`](https://github.com/etalab/codes-postaux) et ça ne retourne rien non plus.

Savez-vous si Saint Martin peut être récupéré ?

Merci beaucoup !

**Comment by totakoko** [comment]
A priori, il manquerait toutes les collectivités d'outre-mer (anciennement territoires d'outre-mer).

cf https://www.insee.fr/fr/information/2028040

Est-ce possible d'intégrer ça au fichier des départements ? Ou bien dans un nouveau fichier ?

**Comment by jdesboeufs** [comment]
Il faudrait rajouter les communes membres de collectivités d'outre-mer.
En effet Saint-Martin est ajouté en dur dans l'API Géo, mais c'est pas du tout satisfaisant.

Si l'un de vous deux est motivé pour créer le fichier `sources/collectivites-outremer.csv`, avec comme colonnes : `code_commune`, `nom_commune`, `code_collectivite`, `nom_collectivite` à partir de la page indiquée par @totakoko, il aura toute mon estime, une bière offert à son prochain passage à Paris ou Metz, et la chance de voir ces données intégrées rapidement dans le dépôt et l'API Géo (je m'y engage).

💆‍♀️

**Comment by AntoineAugusti** [comment]
Je me suis chauffé https://github.com/etalab/decoupage-administratif/pull/2

**Comment by jdesboeufs** [comment]
Voilà https://github.com/etalab/decoupage-administratif/releases/tag/v0.4.0

Merci @AntoineAugusti :)

**Comment by guillett** [comment]
Merci beaucoup !
