### ISSUE TITLE
Code postal dupliqué

### ISSUE THREAD

**Issue by mquandalle** [etalab/decoupage-administratif#29]
La liste des codes postaux inclut souvent le même code postal dupliqué, exemple :

```sh
curl https://unpkg.com/@etalab/decoupage-administratif@1.0.0/data/communes.json | grep Hornoy-le-Bourg

# "codesPostaux":["80640","80640","80640","80640","80640","80640","80640"]
```

(remonté depuis https://github.com/etalab/decoupage-administratif/issues/25#issuecomment-1032632399)

**Comment by ThomasG77** [comment]
Corrigé.

Attention, on a commencé à versionner:

- version 1.x du package qui est pour les données 2021 (34965 communes)
- version 2.x pour les données 2022 (34955 communes)

Merci de confirmer puis fermer si c'est OK

**Comment by mquandalle** [comment]
Je te confirme que c'est corrigé, merci Thomas
